sudo: required

services:
  - docker

before_install:
    - sudo apt-get update

install:
    - sudo apt-get install -y qemu qemu-user-static

script:
  - make test

cache:
  directories:
  - images/*.img
