# SciPy v0.19 & NumPy v1.12.1
#https://github.com/pottava/docker-scipy

# docker run --rm -it pottava/scipy:0.19
# docker run --rm pottava/scipy:0.19 -c 'import scipy; print(scipy.__version__)'
# docker run --rm pottava/scipy:0.19 -c 'import scipy; scipy.show_config()'

FROM alpine:3.5

ENV SCIPY_VERSION=0.19.0 \
    BLAS=/usr/lib/libblas.so \
    LAPACK=/usr/lib/liblapack.so

RUN apk --no-cache add openblas lapack libstdc++ python3 ca-certificates \
    && apk --no-cache add --virtual build-deps lapack-dev python3-dev g++ gfortran \
    && ln -s /usr/include/locale.h /usr/include/xlocale.h \

    # Install SciPy
    && pip3 install "scipy == ${SCIPY_VERSION}" \

    # Clean up
    && find / -type d -name tests -depth -exec rm -rf {} \; \
    && find / -type d -name test -depth -exec rm -rf {} \; \
    && find / -type d -name \__pycache__ -depth -exec rm -rf {} \; \
    && find / -type d -name '*.egg-info' -depth -exec rm -rf {} \; \
    && apk del --purge -r build-deps \
    && rm -rf /root/.cache /usr/include/xlocale.h

ENTRYPOINT ["/usr/bin/python3"]
