version: '2'
services:
  Desktop-1:
    environment:
    - PASSWORD=password
    - USER=user
    cap_add:
    - SYS_PTRACE
    image: cesarandreslopez/docker-ubuntu-mate-desktop-nomachine
    stdin_open: true
    tty: true
    ports:
    - 4000:4000/tcp
