web:
    image: mkenney/base-web:latest
    container_name: www
    ports:
        - "80"
    hostname: docker.webbedlam.com
    volumes:
        - .:/var/www/html/
        - /etc/localtime:/etc/localtime:ro
    environment:
        - server_env=dev
        - env=1
        - is_docker=1
        - DOCUMENTROOT_PATH=/var/www/html/documentroot # Configurable, defaults to
                                                       # /var/www/html/documentroot
        - VIRTUAL_HOST=docker.webbedlam.com # Used in the vhost config and can also
                                            # be used by the mkenney/reverse-proxy
                                            # image
    restart: always

