#!/bin/bash
#清理陈旧停止的容器
# Author: Joe Block <jpb@unixorn.net>
# License: Apache 2 (See LICENSE file)

CONTAINER_LIST=$(docker ps -a -q)

if [ -n "${CONTAINER_LIST}" ]; then
  exec docker rm ${CONTAINER_LIST}
else
  echo "No containers to clean up"
fi
