#!/usr/bin/env bash

# WARNING! This will remove:
        # - all stopped containers
        # - all volumes not used by at least one container
        # - all networks not used by at least one container
        # - all images without at least one container associated to them
# requires docker 1.13

# source common script to set environment
. "$(dirname "$0")/common"

"$docker_bin" system df

"$docker_bin" system prune --all --force
