#!/bin/bash

# https://github.com/ContinuumIO/docker-images/tree/master/anaconda
# Start jupyter notebooks
# docker run -i -t -p 8888:8888 continuumio/anaconda /bin/bash -c "/opt/conda/bin/conda install jupyter -y --quiet && mkdir /opt/notebooks && /opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 --no-browser"

docker run -it -v /tmp:/tmp -p 8888:8888 continuumio/anaconda /bin/bash
