version: "2"
services:

  jupyter:
    build: build
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    ports:
      - "8888:8888"
    volumes:
      - notebook:/workdir

volumes:
  notebook:
    driver: local
