#sudo vim /etc/apt/sources.list

sudo tee /etc/apt/sources.list <<-'EOF'
#https://github.com/luanyata/Source-List-Deepin

## Generated by deepin-installer
#deb [by-hash=force] http://packages.deepin.com/deepin panda main contrib non-free
#deb-src http://packages.deepin.com/deepin panda main contrib non-free


### Repositorio da UFPR
deb [by-hash=force] http://mirrors.aliyun.com/deepin unstable main contrib non-free 
deb-src http://mirrors.aliyun.com/deepin unstable main contrib non-free
#deb-src http://linuxdeepin.c3sl.ufpr.br/deepin panda main contrib non-free


### Repositórios padrão Debian.
deb http://mirrors.aliyun.com/debian/ jessie main non-free contrib
#deb-src http://http.debian.net/debian/ jessie main non-free contrib 

### Atualizações de Segurança.
deb http://security.debian.org/ jessie/updates main contrib non-free
#deb-src http://security.debian.org/ jessie/updates main contrib non-free 

### Volatile (softwares atualizados com frequência, Clamav, etc)
deb http://http.debian.net/debian/ jessie-updates main contrib non-free
#deb-src http://http.debian.net/debian/ jessie-updates main contrib non-free 

### Backports (no momento)
deb http://http.debian.net/debian/ jessie-backports main contrib non-free
#deb-src http://http.debian.net/debian/ jessie-backports main contrib non-free

EOF

