settings:
  resources:
    streams: streams.log
    logs: logs.log
    errors: errors.log
  server:
    enable: false
    open: false
    host: localhost
    port: 5001
  config:
    flimit: 0
projects:
- name: docker-webui
  path: /
  fmt: true
  test: true
  generate: false
  bin: true
  build: false
  run: true
  params: []
  watcher:
    before: []
    after: []
    paths:
    - app/config
    - app/controllers
    - app/engine
    - app/http
    - app/logs
    - app/misc
    - app/models
    ignore_paths:
    - vendor
    exts:
    - .go
    preview: false
  cli:
    streams: true
  file:
    streams: false
    logs: false
    errors: false
