version: "2"
services:

  miniconda2:
    build: miniconda2
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  miniconda3:
    build: miniconda3
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  anaconda2:
    build: anaconda2
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  anaconda3:
    build: anaconda3
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
