version: '2'

services:
    consul:
        image: smebberson/alpine-consul
    consului:
        image: smebberson/alpine-consul-ui
        ports:
            - 8500:8500
    cache:
        image: smebberson/alpine-consul-redis
